version: '2.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
    networks:
      stream-network:
        aliases:
          - zookeeper
    restart: always

  kafka:
    image: wurstmeister/kafka
    depends_on:
        - zookeeper
    ports:
        - "9092:9092"
        - "9094:9094"
    environment:
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_RETENTION_MINUTES: 10
        KAFKA_LOG_SEGMENT_BYTES: 107374182
        KAFKA_NUM_PARTITIONS: 12
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      stream-network:
        aliases:
          - kafka
    restart: always

  webserver:
    image: nginx:latest
    ports:
      - 5001:5001
    restart: always
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d/:ro
      - ${PWD}/static/images/:/www/data/images/

networks:
  stream-network:
    external: true