kafka:
  bootstrap_servers: kafka:9092
  group_id: DEFAULT_KAFKA_GROUP_ID
  image_generation_topic: IMAGE_GENERATION_TOPIC
  text_translation_topic: TEXT_TRANSLATION_TOPIC
  im2im_generation_topic: IMAGE_TO_IMAGE_GENERATION_TOPIC

postgres:
  host: postgres:5432
  database: diff-server
  user: postgres
  password: changeme
  query_meta_table: query_meta

redis:
  host: redis
  port: 6379
  database: 0

server:
  host: 0.0.0.0
  port: 5000

imagen:
  device: cuda:0
  checkpoint: ./checkpoints/fp32

translator:
  device: cuda:0
  checkpoint: checkpoints/translator

file_server:
  folder: ./static/images
