kafka:
  bootstrap_servers: localhost:9094
  group_id: DEFAULT_KAFKA_GROUP_ID
  image_generation_topic: IMAGE_GENERATION_TOPIC
  text_translation_topic: TEXT_TRANSLATION_TOPIC

postgres:
  host: localhost
  database: diff-server
  user: postgres
  password: changeme
  query_meta_table: query_meta

server:
  host: 0.0.0.0
  port: 5000

imagen:
  device: cpu
  checkpoint: checkpoints/fp16

translator:
  device: cpu
  checkpoint: checkpoints/translator

file_server:
  folder: ./static/images